version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - /mosquitto/config:/mosquitto/config
            - /mosquitto/data:/mosquitto/data
        networks:
            - mosquitto
    estoque:
        image: pahomqtt
        #command: sleep 1 && python3 ./estoque_teste.py
    #fabrica1:
        #image: pahomqtt
        #command: sleep 1 && python3 ./fabrica_teste1.py
    fabrica2:
        image: pahomqtt
        command: sleep 1 && python3 ./fabrica_teste2.py
    linha:
        image: pahomqtt
        command: sleep 1 && python3 ./linha_teste.py
    almoxarifado:
        image: pahomqtt
        command: sleep 1 && python3 ./almoxarifado_teste.py
    fornecedor:
        image: pahomqtt
        command: sleep 1 && python3 ./fornecedor_teste.py
networks:
    mosquitto:
        name: mosquitto
        driver: bridge